language: pyhton
python:
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

install:
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
